language: node_js

os:
  - linux
  - windows

node_js:
  - '6'
  - '8'
  - '10'

# https://travis-ci.community/t/files-in-checkout-have-eol-changed-from-lf-to-crlf/349/3
before_install:
  - cd ../..
  - mv $TRAVIS_REPO_SLUG _old
  - git config --global core.autocrlf false
  - git clone --depth=50 _old $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG

install:
  - npm install newman@4.4.0
  - npm install
